config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  resources :items, only: [:index, :new, :create, :update]
  resources :stores, only: [:new, :create, :index, :show ]
  resources :brands, only: [:new, :create, :index ]
  root 'items#index'
  post '/login', to: 'auth#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
   
    belongs_to :store, optional: true
    belongs_to :brand, optional: true

    def brand_attributes=brand_hash
        if !brand_hash[:name].empty?
            brand = Brand.find_or_create_by(name: brand_hash[:name])
            self.brand = brand
        end
    end

    def store_attributes=store_hash
        if !store_hash[:name].empty?
            store = Store.find_or_create_by(name: store_hash[:name])
            self.store = store
        end
    end
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
    @user = User.find_by(username: params[:username])
    
    if !@user
      render json: {
        errors: ["Unable to find a user with the provided email"]         
      }, status: 500

    elsif @user && @user.authenticate(params[:password])
      # render "users/users_with_token.json.jbuilder", user: @user
      render json: @user

    else
      render json: {
        errors: ["Password is incorrect"]        
      }, status: 500
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
    render json: @brands 
  end

  def new
  end

  def create
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    render json: @items 
  end

  def new
    @item = Item.new
    @brand = @item.build_brand
    @store = @item.build_store
  end

  def update
    @item = Item.find_by(id: params[:id])
    if @item.update(item_params)
      render json: @item
    else
      redirect_to items_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      render json: @item
    else
      redirect_to new_item_path
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :cost, :listing_price, :brand_id, :store_id, :sold_price, :listing_date, :brand_attributes => [:name], :store_attributes => [:name])
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
    render json: @stores
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to stores_path
    else
      redirect_to new_store_path
    end
  end

  def show
    @store = Store.find(params[:id])
  end

  private

    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/views/brands/new.html.erb
<h1>Brands#new</h1>
<p>Find me in app/views/brands/new.html.erb</p>

app/views/items/index.html.erb
<h1>Items</h1>
<table id="items" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Cost</th>
      <th scope="col">Listing Price</th>
      <th scope="col">Sold Price</th>
      <th scope="col">Brand</th>
      <th scope="col">Bought</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
        <tr>
        <th scope="row"><%= item.name %></th>
        <td><%= item.cost.format %></td>
        <td><%= item.listing_price.format %></td>
        <td>
          <% if item.sold_price %>
            <%= item.sold_price.format %>
          <% else%>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-<%= item.id %>">
              Sold
            </button>
          <% end %>
        </td>
        <td><%= item.brand.name  %></td>
        <td><%= link_to item.store.name, store_path(item.store)  %></td>
        </tr>
        
        <div class="modal fade" id="modal-<%=item.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sold <%= item.name %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_for item do |f| %>
                  <%= f.number_field :sold_price_cents, :value => '' %>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit 'Save', :class => 'btn btn-success' %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </tbody>
</table>
<%= link_to "New Item", new_item_path, class: "btn btn-primary" %>

app/views/items/new.html.erb
<h2>Create Item</h2>
<%= form_with model: @item do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :cost_cents, 'Cost (in cents)' %>
        <%= f.number_field :cost_cents, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :listing_price_cents, 'Listing Price (in cents)' %>
        <%= f.number_field :listing_price_cents, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :brand  %>
        <%= f.collection_select :brand_id, Brand.all, :id, :name, {include_blank: 'Choose a brand...'}, {:class => 'form-control'} %>
    </div>
    <div class="form-group">
        <%= f.fields_for :brand do |bb| %>
            <%= bb.label :new_brand, 'Or create a new brand...'  %>
            <%= bb.text_field :name, class: 'form-control' %>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.label :store  %>
        <%= f.collection_select :store_id, Store.all, :id, :name, {include_blank: 'Choose a store...'}, {:class => 'form-control'} %>
    </div>
    <div class="form-group">
        <%= f.fields_for :store do |sb| %>
            <%= sb.label :new_store, 'Or create a new store...'  %>
            <%= sb.text_field :name, class: 'form-control' %>
        <% end %>
    </div>
    <%= f.submit 'Create Item', :class => 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sugar and Shane</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Sugar and Shane', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Items', items_path, class: 'nav-link' %> 
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Create new
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'Stores', new_store_path, class: 'dropdown-item' %>
                <%= link_to 'Brands', new_brand_path, class: 'dropdown-item' %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/stores/index.html.erb
<div class='text-center'>
    <h2>My Stores</h2>
    <% @stores.each do |store| %>
        <h3><%= link_to store.name, store_path(store) %>
    <% end %>
</div>

app/views/stores/new.html.erb
<h2>Create Store</h2>
<%= form_with model: @store do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= f.submit 'Create Store', :class => 'btn btn-success' %>
<% end %>

app/views/stores/show.html.erb
<div class="text-center">
  <h2>Products purchased from <%= @store.name %></h2>
  <table  class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Cost</th>
        <th scope="col">Listing Price</th>
        <th scope="col">Sold Price</th>
        <th scope="col">Brand</th>
      </tr>
    </thead>
    <tbody>
      <% @store.items.each do |item| %>
          <tr>
            <th scope="row"><%= item.name %></th>
            <td><%= item.cost.format %></td>
            <td><%= item.listing_price.format %></td>
            <td>
              <% if item.sold_price %>
                <%= item.sold_price.format %>
              <% else%>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-<%= item.id %>">
                  Sold
                </button>
              <% end %>
            </td>
            <td><%= item.brand.name  %></td>
          </tr>
          
          <div class="modal fade" id="modal-<%=item.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Sold <%= item.name %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= form_for item do |f| %>
                    <%= f.number_field :sold_price_cents, :value => '' %>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <%= f.submit 'Save', :class => 'btn btn-success' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </tbody>
  </table>
</div>